version: '3.6'

services:
  img:
    depends_on:
      - elastic
    ports:
      - 4001:4001
    volumes:
      - .:/go/src/analytics
    build:
      context: .
      dockerfile: Dockerfile.img
    command: go run cmd/analytics/img.go

  api:
    depends_on:
      - elastic
    ports:
      - 4002:4002
    volumes:
      - .:/go/src/analytics
    build:
      context: .
      dockerfile: Dockerfile.api
    command: go run cmd/analytics/api.go

  admin:
    depends_on:
      - elastic
    ports:
      - 4003:4003
    volumes:
      - .:/go/src/analytics
    build:
      context: .
      dockerfile: Dockerfile.admin

  elastic:
    image: elasticsearch:7.7.0
    ports:
      - 9200:9200
    environment:
        - node.name=es01
        - discovery.type=single-node
        - cluster.name=es-docker-cluster
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:7.7.0
    ports:
      - 5601:5601
    depends_on:
      - elastic
    environment:
      ELASTICSEARCH_HOSTS: http://elastic:9200

volumes:
  es-data:
