version: '3.0'

services:
  api:
    image: lfv89/analytics-api:0.2
    ports:
      - 80:80
    depends_on:
      - elastic
    environment:
      - PORT=80
      - ELASTIC_URL=elastic:9200
    logging:
      driver: awslogs
      options:
        awslogs-group: analytics
        awslogs-region: us-east-1
        awslogs-stream-prefix: api

  img:
    image: lfv89/analytics-img:0.2
    ports:
      - 8080:8080
    depends_on:
      - elastic
    environment:
      - PORT=8080
      - ELASTIC_URL=elastic:9200
    logging:
      driver: awslogs
      options:
        awslogs-group: analytics
        awslogs-region: us-east-1
        awslogs-stream-prefix: img

  elastic:
    image: elasticsearch:7.7.0
    ports:
      - 9200:9200
    environment:
        - node.name=es01
        - discovery.type=single-node
        - cluster.name=es-docker-cluster
    volumes:
      - es-data:/usr/share/elasticsearch/data
    logging:
      driver: awslogs
      options:
        awslogs-group: analytics
        awslogs-region: us-east-1
        awslogs-stream-prefix: elastic

volumes:
  es-data:
